# Automated Unit Testing Configuration

# Structure of the Tests
# ====================== #
# Switch language runtime (for example, to Ruby 1.9.3 or PHP 5.4)
# Clone project repository from GitHub
# Run before_install scripts (if any)
# cd to the clone directory, run dependencies installation command (default specific to project language)
# Run before_script scripts (if any)
# Run test script command (default is specific to project language). It must use exit code 0 on success and any code on failure.
# Run after_script scripts (if any)

# Tests are run whenever a commit is made to the FoxFire repo #

language: php

# PHP versions to test against
php:
  # Aliased to 5.2.17
  - "5.2"
  # Aliased to a recent 5.3.x version
  - "5.3"
  # Aliased to a recent 5.4.x version
  - "5.4"

# Database is MYSQL
env:
    - DB=mysql

# Execute any number of scripts before the test run, custom env's are available as variables
before_script:
    #- pecl install memcache
    - wget https://raw.github.com/FoxFire/unit-testing/master/setup.sh
    - source setup.sh

# Call Razor
script: php test.php --plugin=foxfire --expertmode --dblogin=root --dbhost=127.0.0.1

notifications:
  email:
    #- If you want notifications, add your email here.
